name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build-and-test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@main
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app
        
    - name: Build and test
      run: xcodebuild clean build test -project EssentialFeed/EssentialFeed.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

